blueprint:
  name: 电视开关
  description: 电视开关事件
  domain: automation
  source_url: https://github.com/shaonianzhentan/xiaomi_tv
  input:
    media_entity:
      name: 电视
      description: 小米电视
      default: []
      selector:
        entity:
          domain: media_player
          device_class: tv
    tv_on:
      name: 打开电视
      description: TV ON
      default: []
      selector:
        action: {}
    tv_off:
      name: 关闭电视
      description: TV OFF
      default: []
      selector:
        action: {}
trigger:
- platform: event
  event_type: xiaomi_tv
  event_data:
    entity_id: !input media_entity
action:
- variables:
    type: '{{ trigger.event.data.type }}'
- choose:
  - conditions:
    - '{{ type == "on" }}'
    sequence: !input 'tv_on'
  - conditions:
    - '{{ type == "off" }}'
    sequence: !input 'tv_off'